installation

In [1]:
# pip install opencv-python
# # # main cv core without extra modules like sift, so run next command
# pip install opencv-contrib-python
# # # numpy
# pip install numpy
# # #  Install Matplotlib (For Displaying Images)
# pip install matplotlib


loading and displaying

In [6]:
import cv2

img = cv2.imread('cat.jpg')

cv2.imshow('cat', img)

print(img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[ 50  66 109]
  [ 49  65 108]
  [ 49  65 108]
  ...
  [117  81  73]
  [114  79  69]
  [115  80  70]]

 [[ 49  65 108]
  [ 49  65 108]
  [ 48  64 107]
  ...
  [118  82  74]
  [114  79  69]
  [115  80  70]]

 [[ 49  65 108]
  [ 48  64 107]
  [ 48  64 107]
  ...
  [118  82  74]
  [114  79  69]
  [116  81  71]]

 ...

 [[ 48  34  36]
  [ 48  34  36]
  [ 48  34  36]
  ...
  [ 60  46  48]
  [ 60  46  48]
  [ 60  46  48]]

 [[ 48  34  36]
  [ 48  34  36]
  [ 48  34  36]
  ...
  [ 59  45  47]
  [ 59  45  47]
  [ 59  45  47]]

 [[ 48  34  36]
  [ 48  34  36]
  [ 48  34  36]
  ...
  [ 58  44  46]
  [ 58  44  46]
  [ 58  44  46]]]


convert to grayscale

In [ ]:
# gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
img = cv2.imread('cat.jpg', 0)

# cv2.imshow('gray img', gray_img)
cv2.imshow('gray img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

resize an image

In [11]:
resized_img = cv2.resize(img, (500,500))
cv2.imshow('resized img', resized_img)
cv2.waitKey(0)
cv2.destroyAllWindows()


edgedetection

In [20]:
edges=cv2.Canny(resized_img,100,200)

cv2.imshow('dfsfd ', edges)
cv2.waitKey(0)
cv2.destroyAllWindows()

features detection

sift

In [25]:
sift = cv2.SIFT_create()

keypoints , descriptors = sift.detectAndCompute(resized_img, None)

img_sift = cv2.drawKeypoints(resized_img, keypoints, None, color=(255,0,0))

print(descriptors)
# print(keypoints)
cv2.imshow('keypoints ', img_sift)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[  0.   0.   0. ...   2.   1.   7.]
 [ 70.   7.   0. ...  28.   3.   1.]
 [ 20.  35.  10. ...  14.   0.   0.]
 ...
 [  0.  53. 146. ...   0.   0.   0.]
 [  1.   0.   0. ...   0.   1.  25.]
 [ 40.  18.  11. ...   0.   0.   0.]]


orb

In [27]:
orb = cv2.ORB_create(nfeatures= 1000)

kp , des = orb.detectAndCompute(resized_img, None)

img_orb = cv2.drawKeypoints(resized_img ,kp , None, color= (0,255,0))

cv2.imshow('keypoints ', img_orb)
cv2.waitKey(0)
cv2.destroyAllWindows()

matching features

In [38]:
img1 = cv2.imread('PS4 resident evil2.jpg', 0)
img2 = cv2.imread('re2.jpg', 0)

orb = cv2.ORB_create(nfeatures= 1000)

kp1 , des1 = orb.detectAndCompute(img1, None)
kp2 , des2 = orb.detectAndCompute(img2, None)

bf = cv2.BFMatcher()
matches = bf.knnMatch(des1, des2 ,k=2)

good = []
for m, n in matches:
    if m.distance < 0.75*n.distance:
        good.append([m])
        
img3= cv2.drawMatchesKnn(img1, kp1, img2, kp2, good, None, flags=2)
print(len(good))

cv2.imshow('matches', cv2.resize(img3,(800,800)))
cv2.waitKey(0)
cv2.destroyAllWindows()

88
